### ISSUE TITLE
PNGs shouldn't be saved with alpha layer

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/ui-screen-shooter#2]
The new iTC won't allow a PNG file with an alpha layer.  The tool should either be changed to remove this layer or save as JPG's instead.

The workaround right now is to open the images in Preview, export to PNG and de-select `Alpha`.

**Comment by ghost** [comment]
This issue has been identified as stale and will be manually closed. This fork will be archived. 

Please refer to the deprecation note in the [canonical repository](https://github.com/jonathanpenn/ui-screen-shooter) for alternatives.
